export { Home } from "./Home"
export { ForgotPasswordPage } from "./ForgotPasswordPage"
export { LoginPage } from "./LoginPage"
export { Profile } from "./Profile"
export { SignUpPage } from "./SignUpPage"
